#!/usr/bin/env bash

REPO="CoryMcCartan/workflow"
KEY="${PWD##*/}"

cat > README.md <<EOF
# \`$KEY\`

## Structure
- \`paper/\`: Paper, final figures and tables
- \`R/\`: Utility functions and code
- \`replication/\`: Main analysis scripts
- \`explore/\`: Intermediate write-ups and exploratory analyses
- \`data-raw/\`: Data used by the analysis
- \`data-out/\`: Data generated by the analysis
EOF

mkdir data-raw
cat > data-raw/README.md <<EOF
# Raw Data

| File | Description | Source |
| ---- | ----------- | ------ |
| \`.parquet\` |  | [link](#) |

These files are not tracked by version control and need to be obtained separately.
EOF

mkdir data-out
cat > data-out/README.md <<EOF
Contains data produced by analyses. Most of these data are not stored in the repository. Those that are are documented below.

| File | Description | Source |
| ---- | ----------- | ------ |
| \`.parquet\` |  | \`R/file.R\` |
EOF

mkdir explore
cat > explore/README.md <<EOF
# Exploratory scripts
EOF

mkdir paper
cd paper
quarto use template --no-prompt --quiet CoryMcCartan/cmc-article
mv paper.qmd "$KEY.qmd"
cd ..

mkdir R
cat > R/README.md <<EOF
# R functions

Utility functions and code, called by replication scripts in \`replication/\`.
EOF

mkdir replication
cat > replication/README.md <<EOF
# Replication code
EOF

mkdir submission

echo folder structure and paper template set up

curl -sO "https://raw.githubusercontent.com/$REPO/refs/heads/main/.gitignore"
git init --quiet
git add .
git commit --quiet -m "Project setup"
echo git repository set up